# Generated by Django 4.2.4 on 2024-11-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='drug',
            name='unique_draft_per_user',
        ),
        migrations.AlterField(
            model_name='drug',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drugillness',
            name='trial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='drug',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'dr')), fields=('creator',), name='unique_draft_per_user'),
        ),
    ]
