# Generated by Django 5.1.6 on 2025-02-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
