# Generated by Django 5.1.6 on 2025-02-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_drug_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='qr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
